// <auto-generated />
using System;
using GamesSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesSharp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219114343_AddGameCategoryAssignments")]
    partial class AddGameCategoryAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamesSharp.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Игральные кости (6-гранные)",
                            Quantity = 100,
                            Type = "Кости"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Игровой таймер",
                            Quantity = 10,
                            Type = "Таймер"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Игровой коврик",
                            Quantity = 5,
                            Type = "Аксессуар"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Фишки (набор)",
                            Quantity = 50,
                            Type = "Фишки"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AverageDuration")
                        .HasColumnType("int");

                    b.Property<int?>("Complexity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .HasColumnType("int");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDuration = 60,
                            Complexity = 3,
                            Description = "Пародийная карточная игра на тему фэнтези-подземелий. Убивай монстров, предавай друзей, хватай сокровища!",
                            MaxPlayers = 6,
                            MinAge = 10,
                            MinPlayers = 3,
                            Name = "Манчкин",
                            PublisherId = 1,
                            YearPublished = 2001
                        },
                        new
                        {
                            Id = 2,
                            AverageDuration = 45,
                            Complexity = 2,
                            Description = "Российская игра на ассоциации с красивыми иллюстрациями. Придумывай ассоциации к картинкам!",
                            MaxPlayers = 7,
                            MinAge = 12,
                            MinPlayers = 4,
                            Name = "Имаджинариум",
                            PublisherId = 1,
                            YearPublished = 2011
                        },
                        new
                        {
                            Id = 3,
                            AverageDuration = 15,
                            Complexity = 1,
                            Description = "Весёлая карточная игра в русскую рулетку с котятами, лазерами и козами",
                            MaxPlayers = 5,
                            MinAge = 7,
                            MinPlayers = 2,
                            Name = "Взрывные котята",
                            PublisherId = 1,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 4,
                            AverageDuration = 15,
                            Complexity = 2,
                            Description = "Командная игра на ассоциации и дедукцию. Угадывай слова по намёкам капитана!",
                            MaxPlayers = 8,
                            MinAge = 10,
                            MinPlayers = 4,
                            Name = "Кодовые имена",
                            PublisherId = 2,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 5,
                            AverageDuration = 75,
                            Complexity = 6,
                            Description = "Классическая стратегия о колонизации острова Катан. Торгуй, строй, побеждай!",
                            MaxPlayers = 4,
                            MinAge = 10,
                            MinPlayers = 3,
                            Name = "Колонизаторы",
                            PublisherId = 1,
                            YearPublished = 1995
                        },
                        new
                        {
                            Id = 6,
                            AverageDuration = 45,
                            Complexity = 1,
                            Description = "Популярная игра в объяснение слов. Объясняй слова, не используя однокоренные!",
                            MaxPlayers = 12,
                            MinAge = 7,
                            MinPlayers = 4,
                            Name = "Элиас",
                            PublisherId = 2,
                            YearPublished = 1993
                        },
                        new
                        {
                            Id = 7,
                            AverageDuration = 30,
                            Complexity = 1,
                            Description = "Знаменитая карточная игра. Избавься от всех карт первым!",
                            MaxPlayers = 10,
                            MinAge = 7,
                            MinPlayers = 2,
                            Name = "Uno",
                            PublisherId = 2,
                            YearPublished = 1971
                        },
                        new
                        {
                            Id = 8,
                            AverageDuration = 40,
                            Complexity = 4,
                            Description = "Игра на выкладывание тайлов средневекового французского ландшафта",
                            MaxPlayers = 5,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Каркассон",
                            PublisherId = 1,
                            YearPublished = 2000
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Игры, требующие стратегического мышления",
                            Name = "Стратегия"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Игры для всей семьи",
                            Name = "Семейная"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Совместные игры",
                            Name = "Кооператив"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Карточные игры",
                            Name = "Карточная"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Легкие игры для компании",
                            Name = "Партийная"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategoryAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("GameCategoryAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameCategoryId = 4,
                            GameId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameCategoryId = 5,
                            GameId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameCategoryId = 4,
                            GameId = 3
                        },
                        new
                        {
                            Id = 4,
                            GameCategoryId = 5,
                            GameId = 4
                        },
                        new
                        {
                            Id = 5,
                            GameCategoryId = 1,
                            GameId = 5
                        },
                        new
                        {
                            Id = 6,
                            GameCategoryId = 5,
                            GameId = 6
                        },
                        new
                        {
                            Id = 7,
                            GameCategoryId = 4,
                            GameId = 7
                        },
                        new
                        {
                            Id = 8,
                            GameCategoryId = 1,
                            GameId = 8
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("GameId");

                    b.ToTable("GameEquipments");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("VenueId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("GamesSharp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FavoriteGenre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GamesSharp.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Россия",
                            FoundedYear = 2009,
                            Name = "Hobby World",
                            Website = "https://www.hobbyworld.ru"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Россия",
                            FoundedYear = 2011,
                            Name = "Cosmodrome Games",
                            Website = "https://cosmodrome.games"
                        },
                        new
                        {
                            Id = 3,
                            Country = "США",
                            FoundedYear = 2002,
                            Name = "Days of Wonder",
                            Website = "https://www.daysofwonder.com"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.SessionPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("bit");

                    b.Property<int?>("Place")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Team")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("RentalCostPerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Арбат, д. 10",
                            Capacity = 30,
                            Name = "Игротека на Арбате",
                            Phone = "+7(495)123-45-67",
                            RentalCostPerHour = 500m
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ленинский пр-т, д. 5",
                            Capacity = 20,
                            Name = "Антикафе Таймкод",
                            Phone = "+7(495)234-56-78",
                            RentalCostPerHour = 300m
                        },
                        new
                        {
                            Id = 3,
                            Address = "пр-т Мира, д. 33",
                            Capacity = 50,
                            Name = "Клуб настольных игр Мосигра",
                            Phone = "+7(495)345-67-89",
                            RentalCostPerHour = 800m
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.HasOne("GamesSharp.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategoryAssignment", b =>
                {
                    b.HasOne("GamesSharp.Models.GameCategory", "GameCategory")
                        .WithMany("GameCategoryAssignments")
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameCategoryAssignments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameCategory");
                });

            modelBuilder.Entity("GamesSharp.Models.GameEquipment", b =>
                {
                    b.HasOne("GamesSharp.Models.Equipment", "Equipment")
                        .WithMany("GameEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameEquipments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Venue", "Venue")
                        .WithMany("GameSessions")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("GamesSharp.Models.SessionPlayer", b =>
                {
                    b.HasOne("GamesSharp.Models.GameSession", "GameSession")
                        .WithMany("SessionPlayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Player", "Player")
                        .WithMany("SessionPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GamesSharp.Models.Equipment", b =>
                {
                    b.Navigation("GameEquipments");
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.Navigation("GameCategoryAssignments");

                    b.Navigation("GameEquipments");

                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategory", b =>
                {
                    b.Navigation("GameCategoryAssignments");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.Navigation("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.Player", b =>
                {
                    b.Navigation("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesSharp.Models.Venue", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
