// <auto-generated />
using System;
using GamesSharp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamesSharp.src.Infrastructure.PersistenceMigrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260420184041_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("GamesSharp.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 2,
                            Name = "США"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EquipmentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentTypeId");

                    b.ToTable("Equipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentTypeId = 1,
                            Name = "Игральные кости (6-гранные)"
                        },
                        new
                        {
                            Id = 2,
                            EquipmentTypeId = 2,
                            Name = "Игровой таймер"
                        },
                        new
                        {
                            Id = 3,
                            EquipmentTypeId = 3,
                            Name = "Игровой коврик"
                        },
                        new
                        {
                            Id = 4,
                            EquipmentTypeId = 4,
                            Name = "Фишки (набор)"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Кости"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Таймер"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Аксессуар"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Фишки"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AverageDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Complexity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YearPublished")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageDuration = 90,
                            Complexity = 3,
                            Description = "Классическая экономическая настольная игра про покупку улиц, аренду и развитие собственности.",
                            MaxPlayers = 6,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Монополия",
                            PublisherId = 1,
                            YearPublished = 1935
                        },
                        new
                        {
                            Id = 2,
                            AverageDuration = 30,
                            Complexity = 1,
                            Description = "Одна из самых популярных карточных игр в России. Цель - избавиться от карт раньше соперников.",
                            MaxPlayers = 6,
                            MinAge = 10,
                            MinPlayers = 2,
                            Name = "Дурак",
                            PublisherId = 1,
                            YearPublished = 1810
                        },
                        new
                        {
                            Id = 3,
                            AverageDuration = 25,
                            Complexity = 1,
                            Description = "Динамичная карточная игра с цветами и действиями, популярная в компаниях и семьях.",
                            MaxPlayers = 10,
                            MinAge = 7,
                            MinPlayers = 2,
                            Name = "Уно",
                            PublisherId = 1,
                            YearPublished = 1971
                        },
                        new
                        {
                            Id = 4,
                            AverageDuration = 45,
                            Complexity = 2,
                            Description = "Популярная российская игра на ассоциации с иллюстрациями.",
                            MaxPlayers = 7,
                            MinAge = 12,
                            MinPlayers = 4,
                            Name = "Имаджинариум",
                            PublisherId = 2,
                            YearPublished = 2011
                        },
                        new
                        {
                            Id = 5,
                            AverageDuration = 40,
                            Complexity = 2,
                            Description = "Командная психологическая игра на обсуждение и дедукцию.",
                            MaxPlayers = 15,
                            MinAge = 12,
                            MinPlayers = 6,
                            Name = "Мафия",
                            PublisherId = 1,
                            YearPublished = 1986
                        },
                        new
                        {
                            Id = 6,
                            AverageDuration = 20,
                            Complexity = 1,
                            Description = "Быстрая карточная игра, очень популярная в российских компаниях.",
                            MaxPlayers = 10,
                            MinAge = 8,
                            MinPlayers = 2,
                            Name = "Свинтус",
                            PublisherId = 2,
                            YearPublished = 2006
                        },
                        new
                        {
                            Id = 7,
                            AverageDuration = 20,
                            Complexity = 2,
                            Description = "Командная игра на ассоциации и дедукцию.",
                            MaxPlayers = 8,
                            MinAge = 10,
                            MinPlayers = 4,
                            Name = "Кодовые имена",
                            PublisherId = 2,
                            YearPublished = 2015
                        },
                        new
                        {
                            Id = 8,
                            AverageDuration = 45,
                            Complexity = 3,
                            Description = "Популярная в России дискуссионная игра на выживание и социальные роли.",
                            MaxPlayers = 16,
                            MinAge = 12,
                            MinPlayers = 4,
                            Name = "Бункер",
                            PublisherId = 1,
                            YearPublished = 2018
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GameCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Игры, требующие стратегического мышления",
                            Name = "Стратегия"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Игры для всей семьи",
                            Name = "Семейная"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Совместные игры",
                            Name = "Кооператив"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Карточные игры",
                            Name = "Карточная"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Легкие игры для компании",
                            Name = "Партийная"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategoryAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameCategoryId");

                    b.HasIndex("GameId");

                    b.ToTable("GameCategoryAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameCategoryId = 1,
                            GameId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameCategoryId = 4,
                            GameId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameCategoryId = 4,
                            GameId = 3
                        },
                        new
                        {
                            Id = 4,
                            GameCategoryId = 5,
                            GameId = 4
                        },
                        new
                        {
                            Id = 5,
                            GameCategoryId = 5,
                            GameId = 5
                        },
                        new
                        {
                            Id = 6,
                            GameCategoryId = 4,
                            GameId = 6
                        },
                        new
                        {
                            Id = 7,
                            GameCategoryId = 5,
                            GameId = 7
                        },
                        new
                        {
                            Id = 8,
                            GameCategoryId = 5,
                            GameId = 8
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.GameEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequiredQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("GameId");

                    b.ToTable("GameEquipments");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualStartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Organizer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SessionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SessionStatusId");

                    b.HasIndex("VenueId");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("GamesSharp.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FavoriteGenre")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1996, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Владимир",
                            Email = "alexey.petrov@example.com",
                            FavoriteGenre = "Стратегия",
                            Name = "Алексей Петров",
                            Phone = "+7(900)111-22-33",
                            RegisteredDate = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1998, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Суздаль",
                            Email = "maria.sokolova@example.com",
                            FavoriteGenre = "Семейная",
                            Name = "Мария Соколова",
                            Phone = "+7(900)222-33-44",
                            RegisteredDate = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1994, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Муром",
                            Email = "ilya.kuznetsov@example.com",
                            FavoriteGenre = "Карточная",
                            Name = "Илья Кузнецов",
                            Phone = "+7(900)333-44-55",
                            RegisteredDate = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2000, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Ковров",
                            Email = "ekaterina.orlova@example.com",
                            FavoriteGenre = "Партийная",
                            Name = "Екатерина Орлова",
                            Phone = "+7(900)444-55-66",
                            RegisteredDate = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1993, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Гусь-Хрустальный",
                            Email = "dmitry.fomin@example.com",
                            FavoriteGenre = "Кооператив",
                            Name = "Дмитрий Фомин",
                            Phone = "+7(900)555-66-77",
                            RegisteredDate = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(1997, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Александров",
                            Email = "olga.nikitina@example.com",
                            FavoriteGenre = "Семейная",
                            Name = "Ольга Никитина",
                            Phone = "+7(900)666-77-88",
                            RegisteredDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(1991, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Боголюбово",
                            Email = "sergey.vlasov@example.com",
                            FavoriteGenre = "Стратегия",
                            Name = "Сергей Власов",
                            Phone = "+7(900)777-88-99",
                            RegisteredDate = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2001, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "Мелехово",
                            Email = "anna.zaitseva@example.com",
                            FavoriteGenre = "Карточная",
                            Name = "Анна Зайцева",
                            Phone = "+7(900)888-99-00",
                            RegisteredDate = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            FoundedYear = 2009,
                            Name = "Hobby World",
                            Website = "https://www.hobbyworld.ru"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            FoundedYear = 2011,
                            Name = "Cosmodrome Games",
                            Website = "https://cosmodrome.games"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            FoundedYear = 2002,
                            Name = "Days of Wonder",
                            Website = "https://www.daysofwonder.com"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.SessionPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsWinner")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.HasIndex("PlayerId");

                    b.ToTable("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.SessionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("SessionStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "scheduled",
                            Name = "Запланирована"
                        },
                        new
                        {
                            Id = 2,
                            Code = "in_progress",
                            Name = "В процессе"
                        },
                        new
                        {
                            Id = 3,
                            Code = "completed",
                            Name = "Завершена"
                        },
                        new
                        {
                            Id = 4,
                            Code = "cancelled",
                            Name = "Отменена"
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RentalCostPerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "г. Владимир, ул. Большая Московская, д. 11",
                            Capacity = 40,
                            Latitude = 56.129100000000001,
                            Longitude = 40.406599999999997,
                            Name = "Клуб настольных игр Владимир",
                            Phone = "+7(492)212-34-56",
                            RentalCostPerHour = 600m
                        },
                        new
                        {
                            Id = 2,
                            Address = "г. Суздаль, ул. Ленина, д. 72",
                            Capacity = 24,
                            Latitude = 56.419499999999999,
                            Longitude = 40.452500000000001,
                            Name = "Игротека Суздаль",
                            Phone = "+7(492)312-45-67",
                            RentalCostPerHour = 450m
                        },
                        new
                        {
                            Id = 3,
                            Address = "г. Муром, ул. Московская, д. 5",
                            Capacity = 30,
                            Latitude = 55.572800000000001,
                            Longitude = 42.052300000000002,
                            Name = "Антикафе Муром",
                            Phone = "+7(492)342-56-78",
                            RentalCostPerHour = 400m
                        },
                        new
                        {
                            Id = 4,
                            Address = "г. Ковров, пр-т Ленина, д. 36",
                            Capacity = 28,
                            Latitude = 56.357199999999999,
                            Longitude = 41.319200000000002,
                            Name = "Игровое пространство Ковров",
                            Phone = "+7(492)322-67-89",
                            RentalCostPerHour = 420m
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.VenueEquipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("VenueId", "EquipmentId")
                        .IsUnique();

                    b.ToTable("VenueEquipments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 1,
                            Quantity = 40,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 2,
                            Quantity = 4,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 3,
                            Quantity = 2,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 4,
                            Quantity = 20,
                            VenueId = 1
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 1,
                            Quantity = 25,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 2,
                            Quantity = 2,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 7,
                            EquipmentId = 4,
                            Quantity = 10,
                            VenueId = 2
                        },
                        new
                        {
                            Id = 8,
                            EquipmentId = 1,
                            Quantity = 60,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 9,
                            EquipmentId = 2,
                            Quantity = 8,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 10,
                            EquipmentId = 3,
                            Quantity = 4,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 11,
                            EquipmentId = 4,
                            Quantity = 35,
                            VenueId = 3
                        },
                        new
                        {
                            Id = 12,
                            EquipmentId = 1,
                            Quantity = 30,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 13,
                            EquipmentId = 2,
                            Quantity = 3,
                            VenueId = 4
                        },
                        new
                        {
                            Id = 14,
                            EquipmentId = 4,
                            Quantity = 16,
                            VenueId = 4
                        });
                });

            modelBuilder.Entity("GamesSharp.Models.Equipment", b =>
                {
                    b.HasOne("GamesSharp.Models.EquipmentType", "EquipmentType")
                        .WithMany("Equipments")
                        .HasForeignKey("EquipmentTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EquipmentType");
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.HasOne("GamesSharp.Models.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategoryAssignment", b =>
                {
                    b.HasOne("GamesSharp.Models.GameCategory", "GameCategory")
                        .WithMany("GameCategoryAssignments")
                        .HasForeignKey("GameCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameCategoryAssignments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameCategory");
                });

            modelBuilder.Entity("GamesSharp.Models.GameEquipment", b =>
                {
                    b.HasOne("GamesSharp.Models.Equipment", "Equipment")
                        .WithMany("GameEquipments")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameEquipments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.HasOne("GamesSharp.Models.Game", "Game")
                        .WithMany("GameSessions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.SessionStatus", "SessionStatus")
                        .WithMany("GameSessions")
                        .HasForeignKey("SessionStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Venue", "Venue")
                        .WithMany("GameSessions")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("SessionStatus");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("GamesSharp.Models.Publisher", b =>
                {
                    b.HasOne("GamesSharp.Models.Country", "Country")
                        .WithMany("Publishers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("GamesSharp.Models.SessionPlayer", b =>
                {
                    b.HasOne("GamesSharp.Models.GameSession", "GameSession")
                        .WithMany("SessionPlayers")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Player", "Player")
                        .WithMany("SessionPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameSession");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GamesSharp.Models.VenueEquipment", b =>
                {
                    b.HasOne("GamesSharp.Models.Equipment", "Equipment")
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GamesSharp.Models.Venue", "Venue")
                        .WithMany("VenueEquipments")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("GamesSharp.Models.Country", b =>
                {
                    b.Navigation("Publishers");
                });

            modelBuilder.Entity("GamesSharp.Models.Equipment", b =>
                {
                    b.Navigation("GameEquipments");
                });

            modelBuilder.Entity("GamesSharp.Models.EquipmentType", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("GamesSharp.Models.Game", b =>
                {
                    b.Navigation("GameCategoryAssignments");

                    b.Navigation("GameEquipments");

                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("GamesSharp.Models.GameCategory", b =>
                {
                    b.Navigation("GameCategoryAssignments");
                });

            modelBuilder.Entity("GamesSharp.Models.GameSession", b =>
                {
                    b.Navigation("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.Player", b =>
                {
                    b.Navigation("SessionPlayers");
                });

            modelBuilder.Entity("GamesSharp.Models.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamesSharp.Models.SessionStatus", b =>
                {
                    b.Navigation("GameSessions");
                });

            modelBuilder.Entity("GamesSharp.Models.Venue", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("VenueEquipments");
                });
#pragma warning restore 612, 618
        }
    }
}
